### ISSUE TITLE
Qualification report QC

### ISSUE THREAD

**Issue by AndreDlm** [Open-Systems-Pharmacology/Pediatric_Qualification_Package_UGT1A1_Ontogeny#2]
Hi @Incei, a few minor issues are highlighted in the attached pdf [here](https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_UGT1A1_Ontogeny/files/7925811/report_AD.pdf)
Thx

**Comment by Yuri05** [comment]
I think all comments were addressed by @Incei in the previous PRs.
@AndreDlm Please check the last report [here](https://github.com/Yuri05/Pediatric_Qualification_Package_UGT1A1_Ontogeny/blob/review/Qualification/report/report.md) and open new issue(s) if anything is still wrong.
